
# Start with 'startx ~/.xinitrc <session>'


# Common settings

# Keyboard repeat rate
xset r rate 200 60

# Set CAPS to CTRL
setxkbmap -option ctrl:nocaps


session=${1:=xfce}

case "$session" in
    xfce|xfce4)
        exec startxfce4 ;;

    emacs|exwm)
        #Disable access control ??
        xhost +SI:localuser:$USER

        # Make Java apps aware this is a non-reparenting window manager
        export _JAVA_AWT_WM_NONREPARENTING=1

        # Themes, etc (TODO: Make it work for xfce4 settings)
        # gnome-settings-daemon &

        # Fallback cursor
        xsetroot -cursor_name left_ptr

        # Adjust monitors just before exwm starts
        $HOME/bin/adjust-monitors.sh

        # Start Emacs
        exec dbus-launch --exit-with-session emacs
        ;;

    awesome)
        exec awesome
        ;;

    bspwm)
        $HOME/bin/adjust-monitors.sh
        sxhkd &
        exec bspwm
        ;;

    qtile)
        # Adjust monitors just before exwm starts
        $HOME/bin/adjust-monitors.sh

        # Start Qtile
        exec qtile
        ;;

    i3|i3wm)
        #$HOME/bin/adjust-monitors.sh

        exec i3
        ;;
    *)
        exec $*
        ;;
esac
