
# Start with 'startx ~/.xinitrc <session>'

# Import X settings
[ -f /etc/xprofile ] && . /etc/xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

session=${1:=xfce}

case "$session" in
    xfce|xfce4)
        exec startxfce4 ;;

    emacs|exwm)
        #Disable access control ??
        xhost +SI:localuser:$USER

        # Make Java apps aware this is a non-reparenting window manager
        export _JAVA_AWT_WM_NONREPARENTING=1

        # Themes, etc (TODO: Make it work for xfce4 settings)
        # gnome-settings-daemon &

        # Fallback cursor
        xsetroot -cursor_name left_ptr

        # Adjust monitors just before exwm starts
        $HOME/bin/adjust-monitors.sh

        # Start Emacs
        exec dbus-launch --exit-with-session emacs
        ;;

    awesome)
        exec awesome
        ;;

    bspwm)
        $HOME/bin/adjust-monitors.sh
        sxhkd &
        exec bspwm
        ;;

    i3|i3wm)
        exec i3
        ;;
    *)
        exec $*
        ;;
esac
