---
- name: Install Neovim
  become: yes
  package:
      name: neovim

- name: Create directory
  file:
      path: "{{ ansible_user_dir }}/.config/nvim"
      state: directory

- name: Place config file
  copy:
      src: init.vim
      dest: "{{ ansible_user_dir }}/.config/nvim/init.vim"