---
- name: Install Vim
  become: yes
  package:
      name: vim

- name: Create directory
  file:
      path: "{{ ansible_user_dir }}/.vim"
      state: directory

- name: Place config file
  copy:
      src: vimrc
      dest: "{{ ansible_user_dir }}/.vimrc"

