---

- name: Check if startx is being used
  stat:
    path: "{{ ansible_user_dir }}/.xinitrc"
  register: startx_st


- name: remove bash_profile if not using startx
  file:
    path: "{{ bash_profile_cfg_path }}"
    state: absent
  when: not startx_st.stat.exists

- name: Add bash_profile if using startx
  assemble:
    remote_src: no
    src: "{{ role_path }}/files/bash_profile"
    dest: "{{ bash_profile_cfg_path }}"
    delimiter: "\n\n"
  register: bprofcfg
  when: startx_st.stat.exists

- debug:
    msg: ".bash_profile was updated"
  when: bprofcfg.changed == true



- name: Assemble profile config if using DM
  assemble:
    remote_src: no
    src: "{{ role_path }}/files/profile"
    dest: "{{ profile_cfg_path }}"
    backup: yes
    delimiter: "\n\n"
  when: not startx_st.stat.exists
  register: profilecfg

- name: Remove profile if using startx
  file:
    path: "{{ profile_cfg_path }}"
    state: absent
  when: startx_st.stat.exists

- debug:
    msg: ".profile was updated. Log in again for changes to take effect"
  when: profilecfg.changed == true



- name: Assemble bashrc config
  assemble:
    remote_src: no
    src: "{{ role_path }}/files/rc"
    dest: "{{ bashrc_cfg_path }}"
    backup: yes
    delimiter: "\n\n"
  register: rccfg

- debug:
    msg: ".bashrc was updated"
  when: rccfg.changed == true