---
# To really apply
# ansible-playbook playbooks/diff_bash.yaml --extra-vars '{really_apply: true}'
- name: Apply diff from working files
  hosts: 127.0.0.1
  connection: local
  vars:
    bash_role_files: "{{ playbook_dir }}/roles/bash/files" 
    really_apply: false
  tasks:
  - name: Get diff
    command: "diff {{ bash_role_files }}/{{ item }} .{{ item }}"
    args:
      chdir: "{{ ansible_user_dir }}"
    failed_when: "diff.rc > 1"
    register: diff
    loop:
      - bashrc
      - bash_profile
      - profile
      - bash_aliases

  - name: debug output
    debug:
      msg: "{{ diff }}"
  
  - name: Apply the diff to the repo
    copy:
      src: "{{ ansible_user_dir }}/.{{ item.item }}"
      dest: "{{ bash_role_files }}/{{ item.item }}"
      remote_src: yes
    when:
      - really_apply == true
      - item.rc == 1
    loop: "{{ diff.results|flatten }}"
  
  - debug:
      msg: "To apply changes from working files, issue \"ansible-playbook playbooks/diff_bash.yaml --extra-vars '{really_apply: true}'\""
    when: not really_apply